version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: container-dev
  ignore:
  - dependency-name: jquery
    versions:
    - 3.5.0
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: container-dev
  ignore:
  - dependency-name: bootstrap_form
    versions:
    - 4.5.0
  - dependency-name: rails
    versions:
    - 5.2.4.4
    - 5.2.4.5
    - 6.1.3
  - dependency-name: listen
    versions:
    - 3.4.1
  - dependency-name: rack
    versions:
    - 2.2.3
  - dependency-name: uglifier
    versions:
    - 4.2.0
  - dependency-name: icalendar
    versions:
    - 2.7.0
