version: '3'
services:
  db:
    image: postgres
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
    volumes:
      - postgresData:/var/lib/postgresql/data
      - /mnt/user/appdata/postgres/db_backups:/home/backups/database/postgresql
    ports:
      - "5432:5432"

  web_prod:
    image: registry.agoralogic.com:5000/ck80/f1tips:76
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
    command: bundle exec rails s -e production -p 3000 -b '0.0.0.0'
    volumes:
      - ${PWD}/config/secrets.yml.key:/myapp/config/secrets.yml.key
#      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - f1appprodenv.env

  web_dev:
    image: registry.agoralogic.com:5000/ck80/f1tips:latest
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
    command: bundle exec rails s -e development -p 3080 -b '0.0.0.0'
#    volumes:
#      - .:/myapp
    ports:
      - "3080:3080"
    depends_on:
      - db
    env_file:
      - f1appdevenv.env

volumes:
  postgresData:
