version: '3'
services:
#  db:
#    image: postgres
#    volumes:
#      - postgresData:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#  web_prod:
#    build: .
#    command: bundle exec rails s -e production -p 3080 -b '0.0.0.0'
#    volumes:
#      - .:/myapp
#    ports:
#      - "3080:3080"
#    depends_on:
#      - db
#    env_file:
#      - f1appprodenv.env

  web_dev:
    image: localhost:5000/ck/f1tips
    command: bundle exec rails s -e development -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
#    depends_on:
#      - db
    env_file:
      - f1appdevenv.env

#volumes:
#  postgresData: